esphome:
  name: "esphome-web-aircon"
  comment: "ESPHome configuration for AirCon Keypad"
  area: Hallway
  friendly_name: ESPHome - Actron Air
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Aircon-Keypad Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80

# Setup i2c bus to controll MCP4725
i2c:
  sda: GPIO21
  scl: GPIO22

# MCP4725 output to send voltages for key presses
output:
  - platform: mcp4725
    id: dac_output

globals:
  - id: dac_value
    type: double
  - id: prev_fan
    type: std::string
    initial_value: '"Unset"'
  # DAC voltage values for button presses (in millivolts)
  - id: voltage_power
    type: double
    initial_value: "5000.0"
    # Panel: 0
  - id: voltage_fan
    type: double
    initial_value: "755.0"
  - id: voltage_mode
    type: double
    initial_value: "620.0"
  - id: voltage_temp_up
    type: double
    initial_value: "889.0"
  - id: voltage_temp_down
    type: double
    initial_value: "782.0"
  - id: voltage_timer
    type: double
    initial_value: "862"
  - id: voltage_timer_up
    type: double
    initial_value: "828.0"
  - id: voltage_timer_down
    type: double
    initial_value: "808.0"
  - id: voltage_zone_1
    type: double
    initial_value: "725.0"
  - id: voltage_zone_2
    type: double
    initial_value: "663.0"
  - id: voltage_zone_3
    type: double
    initial_value: "695.0"
  # NOTE: Add more zones as needed

# Testing: DAC output control
number:
  - platform: template
    name: "DAC Output milliVolts"
    icon: mdi:flash-triangle
    min_value: 0
    max_value: 5000
    step: 0.1
    optimistic: true
    on_value:
      then:
        lambda: |-
          id(dac_output).set_level((x / 5000.0));

# Internal button for press action
button:
  - platform: template
    name: "Press"
    id: press_button
    internal: true
    icon: mdi:power
    on_press:
      - logger.log: Button Pressed
      - lambda: |-
          id(dac_output).set_level((id(dac_value) / 5000.0));
      - delay: 250ms
      - lambda: |-
          id(dac_output).set_level((0.0 / 5000.0));
      - delay: 250ms

  - platform: template
    name: "Fan"
    icon: mdi:fan
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_fan);
          id(press_button).press();

  - platform: template
    name: "Mode"
    icon: mdi:air-conditioner
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_mode);
          id(press_button).press();

  - platform: template
    name: "Temp Up"
    icon: mdi:thermometer-plus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_temp_up);
          id(press_button).press();

  - platform: template
    name: "Temp Down"
    icon: mdi:thermometer-minus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_temp_down);
          id(press_button).press();

  - platform: template
    name: "Timer"
    icon: mdi:timer
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer);
          id(press_button).press();

  - platform: template
    name: "Timer Up"
    icon: mdi:timer-plus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer_up);
          id(press_button).press();

  - platform: template
    name: "Timer Down"
    icon: mdi:timer-minus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer_down);
          id(press_button).press();

# Power and zone control switches
switch:
  - platform: template
    icon: mdi:power
    id: power
    name: "Power"
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_power);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_power);
          id(press_button).press();
    lambda: |-
      return (id(cool).state or id(auto_mode).state or id(heat).state or id(fan_cont).state or id(fan_high).state or id(fan_mid).state or id(fan_low).state);

  - platform: template
    id: zone_1_switch
    name: "Zone 1"
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_1);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_1);
          id(press_button).press();
    lambda: return id(zone_1).state;

  - platform: template
    id: zone_2_switch
    name: "Zone 2"
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_2);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_2);
          id(press_button).press();
    lambda: return id(zone_2).state;

  - platform: template
    id: zone_3_switch
    name: "Zone 3"
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_3);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone_3);
          id(press_button).press();
    lambda: return id(zone_3).state;
  # NOTE: Add more zones as needed

external_components:
  - source: github://johnf/esphome_actron_air_keypad
    components: [actron_air_esphome]
    refresh: 0s

actron_air_esphome:
  id: actron_air_esphome_1
  pin: GPIO32

# Sensors from keypad status component
sensor:
  - platform: actron_air_esphome
    setpoint_temp:
      name: "Setpoint Temperature"
      id: setpoint_temp
      icon: mdi:thermometer
    error_count:
      name: "Error Count"
      id: error_count
  # https://esphome.io/components/sensor/adc/?highlight=gpio+sensor
  #- platform: adc
  #  pin: GPIO33
  #  name: "Aircon Wall Panel - Key Press"
  #  update_interval: 250ms
  #  accuracy_decimals: 3
  #  attenuation: auto
  #  filters:
  #  - multiply: 5

text_sensor:
  - platform: actron_air_esphome
    bit_string:
      name: "Bit String"
      id: bit_string
      internal: true

  - platform: template
    name: "Fan Mode"
    update_interval: 1s
    lambda: |-
      std::string current_fan = "";
      if (id(fan_high).state and !id(fan_cont).state) {
        current_fan="High";
      } else if (id(fan_mid).state and !id(fan_cont).state) {
        current_fan="Medium";
      } else if (id(fan_low).state and !id(fan_cont).state) {
        current_fan="Low";
      } else if (id(fan_high).state and id(fan_cont).state) {
        current_fan="High Cont";
      } else if (id(fan_mid).state and id(fan_cont).state) {
        current_fan="Medium Cont";
      } else if (id(fan_low).state and id(fan_cont).state) {
        current_fan="Low Cont";
      } else {
        current_fan="Off";
      }
      if (current_fan.compare(id(prev_fan)) != 0) {
        id(prev_fan) = current_fan;
        return {current_fan};
      }
      return {};

binary_sensor:
  - platform: actron_air_esphome
    room:
      id: room
      name: "Room"
    fan_cont:
      id: fan_cont
      name: "Fan Cont"
      icon: mdi:fan-chevron-up
    fan_high:
      id: fan_high
      name: "Fan High"
      icon: mdi:fan-speed-3
    fan_mid:
      id: fan_mid
      name: "Fan Mid"
      icon: mdi:fan-speed-2
    fan_low:
      id: fan_low
      name: "Fan Low"
      icon: mdi:fan-speed-1
    cool:
      id: cool
      name: "Cool"
      icon: mdi:snowflake
    auto_mode:
      id: auto_mode
      name: "Auto"
      icon: mdi:flash-auto
    heat:
      id: heat
      name: "Heat"
      icon: mdi:fire
    run:
      id: run
      name: "Run"
      icon: mdi:run
    timer:
      id: timer
      name: "Timer"
    inside:
      id: inside
      name: "Inside"
    zone1:
      id: zone_1
      name: "Zone 1"
    zone2:
      id: zone_2
      name: "Zone 2"
    zone3:
      id: zone_3
      name: "Zone 3"
  # NOTE: Add more zones as needed
