# ESPHome Actron Air Keypad Example Configuration
#
# This example shows how to use the actron_air_keypad package.
# Copy this file and customise for your setup.
#
# Optional substitution overrides (uncomment to customise):
# substitutions:
#   gpio_keypad_pin: "GPIO32"
#   gpio_i2c_sda: "GPIO21"
#   gpio_i2c_scl: "GPIO22"
#   # Voltage calibration (millivolts)
#   voltage_power: "5000.0"
#   voltage_fan: "755.0"
#   voltage_mode: "620.0"
#   voltage_temp_up: "889.0"
#   voltage_temp_down: "782.0"
#   voltage_timer: "862"
#   voltage_timer_up: "828.0"
#   voltage_timer_down: "808.0"
#   voltage_zone_1: "725.0"
#   voltage_zone_2: "663.0"
#   voltage_zone_3: "695.0"
#   voltage_zone_4: "650.0"
#   voltage_zone_5: "635.0"
#   voltage_zone_6: "620.0"
#   voltage_zone_7: "605.0"

packages:
  actron_air: github://johnf/actron-air-esphome/actron_air_keypad.yaml@main

esphome:
  name: "esphome-web-aircon"
  comment: "ESPHome configuration for AirCon Keypad"
  area: Hallway
  friendly_name: ESPHome - Actron Air
  min_version: 2025.11.0
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Aircon-Keypad Fallback Hotspot"
    password: !secret wifi_ap_password

# Optional: mDNS service discovery
mdns:
  services:
    - service: "_actron_air"
      protocol: "_tcp"
      port: 6053
      txt:
        version: "1.0.0"
        name: "esphome-web-aircon"

# Optional: Remove unused zones (example for a 3-zone system)
# Uncomment the sections below to remove zones 4-7 from Home Assistant
#
# switch:
#   - id: !remove zone_4_switch
#   - id: !remove zone_5_switch
#   - id: !remove zone_6_switch
#   - id: !remove zone_7_switch
#
# binary_sensor:
#   - id: !remove zone_4
#   - id: !remove zone_5
#   - id: !remove zone_6
#   - id: !remove zone_7
