esphome:
  name: "esphome-web-aircon"
  comment: "ESPHome configuration for AirCon Keypad"
  area: Hallway
  friendly_name: ESPHome - AirCon
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:
  # level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Aircon-Keypad Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80

# Setup i2c bus to controll MCP4725
i2c:
  sda: GPIO21
  scl: GPIO22

# MCP4725 output to send voltages for key presses
output:
  - platform: mcp4725
    id: dac_output

globals:
  - id: dac_value
    type: double
  - id: prev_fan
    type: std::string
    initial_value: '"Unset"'
  # DAC voltage values for button presses (in millivolts)
  - id: voltage_power
    type: double
    initial_value: "5000.0"
  - id: voltage_fan
    type: double
    initial_value: "740.0"
  - id: voltage_mode
    type: double
    initial_value: "943.0"
  - id: voltage_temp_up
    type: double
    initial_value: "884.0"
  - id: voltage_temp_down
    type: double
    initial_value: "769.0"
  - id: voltage_timer
    type: double
    initial_value: "800.0"
  - id: voltage_timer_up
    type: double
    initial_value: "850.0"
  - id: voltage_timer_down
    type: double
    initial_value: "900.0"
  - id: voltage_zone1
    type: double
    initial_value: "715.0"
  - id: voltage_zone2
    type: double
    initial_value: "657.0"
  - id: voltage_zone3
    type: double
    initial_value: "692.0"

# Testing: DAC output control
number:
  - platform: template
    name: "DAC Output milliVolts"
    icon: mdi:flash-triangle
    min_value: 0
    max_value: 5000
    step: 0.1
    optimistic: true
    on_value:
      then:
        lambda: |-
          id(dac_output).set_level((x / 5000.0));

# Internal button for press action
button:
  - platform: template
    name: "Press"
    id: press_button
    internal: true
    icon: mdi:power
    on_press:
      - logger.log: Button Pressed
      - lambda: |-
          id(dac_output).set_level((id(dac_value) / 5000.0));
      - delay: 500ms
      - lambda: |-
          id(dac_output).set_level((0.0 / 5000.0));
      - delay: 500ms

  - platform: template
    name: "Fan"
    icon: mdi:fan
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_fan);
          id(press_button).press();

  - platform: template
    name: "Mode"
    icon: mdi:air-conditioner
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_mode);
          id(press_button).press();

  - platform: template
    name: "Temp Up"
    icon: mdi:thermometer-plus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_temp_up);
          id(press_button).press();

  - platform: template
    name: "Temp Down"
    icon: mdi:thermometer-minus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_temp_down);
          id(press_button).press();

  - platform: template
    name: "Timer"
    icon: mdi:timer
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer);
          id(press_button).press();

  - platform: template
    name: "Timer Up"
    icon: mdi:timer-plus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer_up);
          id(press_button).press();

  - platform: template
    name: "Timer Down"
    icon: mdi:timer-minus
    on_press:
      - lambda: |-
          id(dac_value)=id(voltage_timer_down);
          id(press_button).press();

# Power and zone control switches
switch:
  - platform: template
    name: Power
    icon: mdi:power
    id: power
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_power);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_power);
          id(press_button).press();
    lambda: |-
      return (id(cool).state or id(auto_mode).state or id(heat).state or id(fan_cont).state or id(fan_high).state or id(fan_mid).state or id(fan_low).state);

  - platform: template
    name: "Zone 1"
    id: zone1_switch
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone1);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone1);
          id(press_button).press();
    lambda: return id(zone1).state;

  - platform: template
    name: "Zone 2"
    id: zone2_switch
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone2);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone2);
          id(press_button).press();
    lambda: return id(zone2).state;

  - platform: template
    name: "Zone 3"
    id: zone3_switch
    icon: mdi:air-conditioner
    turn_on_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone3);
          id(press_button).press();
    turn_off_action:
      - lambda: |-
          id(dac_value)=id(voltage_zone3);
          id(press_button).press();
    lambda: return id(zone3).state;

external_components:
  - source: github://johnf/esphome-actron-air-keypad
    components: [actron_air_keypad]

actron_air_keypad:
  id: actron_air_keypad_1
  pin: GPIO33

# Sensors from keypad status component
sensor:
  - platform: actron_air_keypad
    setpoint_temp:
      name: "Setpoint Temperature"
      id: setpoint_temp
      icon: mdi:thermometer
    bit_count:
      name: "Bit Count"
      id: bit_count

# Text sensors from keypad status component
text_sensor:
  - platform: actron_air_keypad
    bit_string:
      name: "Bit String"
      id: bit_string
      internal: true

  - platform: template
    name: "Fan Mode"
    update_interval: 1s
    lambda: |-
      std::string current_fan = "";
      if (id(fan_high).state and !id(fan_cont).state) {
        current_fan="High";
      } else if (id(fan_mid).state and !id(fan_cont).state) {
        current_fan="Medium";
      } else if (id(fan_low).state and !id(fan_cont).state) {
        current_fan="Low";
      } else if (id(fan_high).state and id(fan_cont).state) {
        current_fan="High Cont";
      } else if (id(fan_mid).state and id(fan_cont).state) {
        current_fan="Medium Cont";
      } else if (id(fan_low).state and id(fan_cont).state) {
        current_fan="Low Cont";
      } else {
        current_fan="Off";
      }
      if (current_fan.compare(id(prev_fan)) != 0) {
        id(prev_fan) = current_fan;
        return {current_fan};
      }
      return {};

# Binary sensors from keypad status component
binary_sensor:
  - platform: actron_air_keypad
    room:
      name: "Room"
      id: room
    fan_cont:
      name: "Fan Continuous"
      icon: mdi:fan-chevron-up
      id: fan_cont
    fan_high:
      name: "Fan High"
      icon: mdi:fan-speed-3
      id: fan_high
    fan_mid:
      name: "Fan Mid"
      icon: mdi:fan-speed-2
      id: fan_mid
    fan_low:
      name: "Fan Low"
      icon: mdi:fan-speed-1
      id: fan_low
    cool:
      name: "Cool"
      icon: mdi:snowflake
      id: cool
    auto_mode:
      name: "Auto"
      icon: mdi:flash-auto
      id: auto_mode
    heat:
      name: "Heat"
      icon: mdi:fire
      id: heat
    run:
      name: "Run"
      icon: mdi:run
      id: run
    timer:
      name: "timer"
      id: timer
    filter:
      name: "Filter"
      id: filter
    zone1:
      name: "Zone Bedrooms"
      id: zone1
      icon: mdi:bed
    zone2:
      name: "Zone Living Room"
      id: zone2
      icon: mdi:sofa
    zone3:
      name: "Zone Office"
      id: zone3
      icon: mdi:chair-rolling
    zone4:
      name: "Zone 4"
      id: zone4
      icon: mdi:alert
    zone5:
      name: "Zone 5"
      id: zone5
      icon: mdi:alert
    zone6:
      name: "Zone 6"
      id: zone6
      icon: mdi:alert
    zone7:
      name: "Zone 7"
      id: zone7
      icon: mdi:alert
    # zone8:
    #   name: "Zone 8"
    #   id: zone8
    #   icon: mdi:alert
